Guest_list= ['mom','deborah','kisaki','ella','oluchi','chika']
print(f'Good day {Guest_list[0].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[1].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[2].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[3].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[4].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[5].title()}, would you be available for dinner tonight ')
print(f'\nUnfortunately, {Guest_list[-3].title()} would not be able to make it for dinner')
Guest_list[-3]='Ore'
print(f'\nGood day {Guest_list[0].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[1].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[2].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[3].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[4].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[5].title()}, would you be available for dinner tonight ')
print('\nI just found a bigger dinner table so I would love to invite more guests')
Guest_list.insert(0,'favour')
Guest_list.insert(4,'munirat')
Guest_list.append('niri')
print(f'\nGood day {Guest_list[0].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[1].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[2].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[3].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[4].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[5].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[6].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[7].title()}, would you be available for dinner tonight ')
print(f'Good day {Guest_list[8].title()}, would you be available for dinner tonight ')
print(len(Guest_list))
print('\nUnfortunately I can only invite 2 new guests')
niri=Guest_list.pop(8)
print(f'\nUnfortunately {niri.title()}, I can no longer invite you to dinner')
chika=Guest_list.pop(7)
print(f'Unfortunately {chika.title()}, I can no longer invite you to dinner')
oluchi=Guest_list.pop(6)
print(f'Unfortunately {oluchi.title()}, I can no longer invite you to dinner')
munirat=Guest_list.pop(4)
print(f'Unfortunately {munirat.title()}, I can no longer invite you to dinner')
kisaki=Guest_list.pop(3)
print(f'Unfortunately {kisaki.title()}, I can no longer invite you to dinner')
deborah=Guest_list.pop(2)
print(f'Unfortunately {deborah.title()}, I can no longer invite you to dinner')
favour=Guest_list.pop(0)
print(f'Unfortunately {favour.title()}, I can no longer invite you to dinner')
print(f'\nGood day {Guest_list[0]}, I hope I will be seeing you tonight for dinner')
print(f'Good day {Guest_list[1]}, I hope I will be seeing you tonight for dinner')
del Guest_list[0]
del Guest_list[0]
print(Guest_list)
