vacation= ['seychelles','switzerland','mauritus','japan','dubai']
print(vacation)
print(sorted(vacation))
print(vacation)
print(sorted(vacation,reverse=True))
print(vacation)
vacation.reverse()
print(vacation)
vacation.reverse()
print(vacation)
vacation.sort()
print(vacation)
vacation.sort(reverse=True)
print(vacation)